TERM_PROGRAM=vscode
TERM=xterm-256color
SHELL=/bin/zsh
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000cdhc0033c3/T/
TERM_PROGRAM_VERSION=1.71.2
ZDOTDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000cdhc0033c3/T/vscode-zsh
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
MallocNanoZone=0
USER=abdamoha
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.VYipK4Dlg9/Listeners
__CF_USER_TEXT_ENCODING=0x18D83:0x0:0x0
PATH=/Users/abdamoha/.docker/bin:/Users/abdamoha/.docker/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Users/abdamoha/.docker/bin:/Users/abdamoha/42-ValgrindContainer:/Users/abdamoha/42-ValgrindContainer:/Users/abdamoha/42-ValgrindContainer
PWD=/Users/abdamoha/Desktop/cursus/minishell
LANG=en_US.UTF-8
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
VSCODE_INJECTION=1
SHLVL=2
HOME=/Users/abdamoha
VSCODE_GIT_ASKPASS_MAIN=/private/var/folders/zz/zyxvpxvq6csfxvn_n000cdhc0033c3/T/AppTranslocation/6108952C-C6AE-4625-826E-D6CB6237DB2C/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
LOGNAME=abdamoha
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000cdhc0033c3/T/vscode-git-d71c62c46c.sock
VSCODE_GIT_ASKPASS_NODE=/private/var/folders/zz/zyxvpxvq6csfxvn_n000cdhc0033c3/T/AppTranslocation/6108952C-C6AE-4625-826E-D6CB6237DB2C/d/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
GIT_ASKPASS=/private/var/folders/zz/zyxvpxvq6csfxvn_n000cdhc0033c3/T/AppTranslocation/6108952C-C6AE-4625-826E-D6CB6237DB2C/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
COLORTERM=truecolor
_=/usr/bin/env
